# Generated by Django 3.0.4 on 2020-03-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_update', models.DateTimeField(auto_now=True, null=True)),
                ('gmt_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('username', models.CharField(max_length=64)),
                ('content', models.TextField(max_length=65535)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
